#!/usr/bin/env python3
"""Prove that a golden about to be written came from the pinned baseline.

Goldens are only worth anything if they record what the *pre-restructure* translator
produced. Nothing downstream can check that: a golden generated by the current build has
the right shape, hashes consistently, and passes `verify` forever, because `verify`
compares the current build against it. The claim has to be established at the moment of
generation or not at all.

The invariant is **source identity**, not directory location: the DALiuGE the CLI will
run must be byte-identical to `daliuge_baseline_commit` over `daliuge-*/dlg`. Checking a
worktree's `git rev-parse HEAD` instead is checking a proxy — HEAD says nothing about
uncommitted edits, and nothing at all about which CLI the caller actually passed.

So this walks the other way round. It asks the CLI where its own `dlg` package lives,
finds the repository containing it, and holds *that* repository to the pin. Two setups
pass, and they are the same test:

* a separate checkout at the baseline commit, installed editable into its own venv — the
  general case, and the only one available once a phase has landed;
* this very worktree, while it still carries no translator change from the baseline —
  which is how the Phase 0 corpus was generated, no checkout dance required.

There is deliberately no override. A pin that can be waived is not a pin, and the
legitimate way to move the baseline already exists: edit `PINS` in `manifest.py`, which
is reviewed as code, and the check then holds generation to the new commit.
"""

import subprocess
import sys
from pathlib import Path

try:                                    # `python3 -m tools.provenance`, and type checkers
    from .cases import dlg_executable
    from .manifest import PINS
except ImportError:                     # `python3 tools/provenance.py`
    from cases import dlg_executable  # type: ignore[import-not-found,no-redef]
    from manifest import PINS  # type: ignore[import-not-found,no-redef]

# The translator source the goldens depend on. `daliuge-engine` is excluded: the corpus
# drives the CLI and the translator's REST app, neither of which imports it.
SOURCE_PATHS = ["daliuge-common/dlg", "daliuge-translator/dlg"]


class ProvenanceError(RuntimeError):
    """The CLI about to generate goldens is not the pinned baseline."""


def _git(repository: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", "-C", str(repository), *args],
                          capture_output=True, text=True, check=False)


def _interpreter_for(cli: Path) -> Path:
    """The interpreter a console script runs under, read from its shebang.

    Asking the CLI rather than assuming: `dlg` may sit in a venv that has nothing to do
    with the interpreter running this tooling, which is exactly the case a legacy
    checkout creates.
    """
    try:
        first = cli.read_text(errors="replace").splitlines()[0]
    except (OSError, IndexError) as error:
        raise ProvenanceError(f"cannot read {cli}: {error}") from error
    if not first.startswith("#!"):
        raise ProvenanceError(f"{cli} is not a console script (no shebang)")
    return Path(first[2:].strip().split()[0])


def translator_source(cli: str) -> Path:
    """Where the `dlg` package that `cli` will import actually lives on disk."""
    python = _interpreter_for(Path(cli))
    located = subprocess.run(
        [str(python), "-c", "import dlg.dropmake.pg_generator as m; print(m.__file__)"],
        capture_output=True, text=True, check=False)
    if located.returncode != 0:
        raise ProvenanceError(
            f"{cli} cannot import the translator:\n{located.stderr.strip()}")
    return Path(located.stdout.strip()).resolve()


def source_repository(source: Path) -> Path:
    """The git repository holding `source`.

    A non-editable install lands in site-packages and has no repository, so its
    provenance cannot be established from disk at all — which is a refusal, not a pass.
    """
    top = _git(source.parent, "rev-parse", "--show-toplevel")
    if top.returncode != 0:
        raise ProvenanceError(
            f"the translator at {source} is not inside a git repository, so its "
            f"provenance cannot be checked. Install the baseline checkout editable "
            f"(pip install -e) rather than as a copy.")
    return Path(top.stdout.strip()).resolve()


def assert_baseline(cli: str | None = None, legacy_repo: Path | None = None) -> Path:
    """Raise unless the CLI's translator source is the pinned baseline.

    Returns the repository it was satisfied by, for the caller to report.
    """
    cli = cli or dlg_executable()
    pin = PINS["daliuge_baseline_commit"]

    source = translator_source(cli)
    repository = source_repository(source)

    if legacy_repo is not None:
        expected = legacy_repo.resolve()
        if repository != expected:
            raise ProvenanceError(
                f"--legacy-repo does not hold the translator this CLI runs:\n"
                f"  dlg CLI:        {cli}\n"
                f"  its translator: {source}\n"
                f"  its repository: {repository}\n"
                f"  --legacy-repo:  {expected}")

    if _git(repository, "cat-file", "-e", f"{pin}^{{commit}}").returncode != 0:
        raise ProvenanceError(
            f"{repository} does not contain the baseline commit {pin[:12]}, so the "
            f"translator it holds cannot be compared against it.")

    changed = _git(repository, "diff", "--name-only", pin, "HEAD", "--", *SOURCE_PATHS)
    if changed.returncode != 0:
        raise ProvenanceError(f"cannot diff {repository} against {pin[:12]}: "
                              f"{changed.stderr.strip()}")
    if changed.stdout.strip():
        raise ProvenanceError(
            f"{repository} carries translator changes from the baseline "
            f"{pin[:12]}:\n  " + "\n  ".join(changed.stdout.split()) +
            "\n\nGoldens must record what the baseline produced. Generate from a "
            "checkout of that commit, installed editable into its own environment, and "
            "point DLG_CLI at its dlg.")

    # HEAD matching the pin says nothing about what is on disk, and an editable install
    # runs what is on disk.
    dirty = _git(repository, "status", "--porcelain", "--", *SOURCE_PATHS)
    if dirty.stdout.strip():
        raise ProvenanceError(
            f"{repository} has uncommitted translator changes, so its history does not "
            f"describe what would run:\n  " + "\n  ".join(dirty.stdout.strip().splitlines()))

    return repository


def describe(cli: str, repository: Path) -> str:
    return (f"generating from {cli}\n"
            f"  translator: {repository} @ {PINS['daliuge_baseline_commit'][:12]} "
            f"(baseline, clean)")


if __name__ == "__main__":
    try:
        cli = dlg_executable()
        print(describe(cli, assert_baseline(cli)))
    except ProvenanceError as error:
        print(error, file=sys.stderr)
        raise SystemExit(1) from error
    raise SystemExit(0)
